"""Initial migration

Revision ID: 76d4fc6cfda3
Revises: 809e071015fa
Create Date: 2025-03-23 15:39:51.438260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76d4fc6cfda3'
down_revision: Union[str, None] = '809e071015fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_contacts_phone_number', table_name='contacts')
    op.drop_column('contacts', 'additional_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('additional_info', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_contacts_phone_number', 'contacts', ['phone_number'], unique=False)
    # ### end Alembic commands ###
